from quiz import Question

questions = [Question("What is the capital city of South Australia (SA)?", ["Hobart", "Darwin", "Adelaide", "Brasbaine"], "Adelaide", "Australia"),
            Question("What is the capital city of Tasmania?", ["Sydney", "Hobart", "Canberra", "Adelaide"], "Hobart", "Australia"),
            Question("What is the capital city of Western Australia (WA)?", ["Perth", "Sydney", "Melbourne", "Darwin"], "Perth", "Australia"),
            Question("Which state would you go to if you wanted to see Uluru?", ["Australian Capital Territory (ACT)", "Northern Territory (NT)", "Western Australian (WA)", "New South West (NSW)"], "Northern Territory NT", "Australia"),
            Question("In which state would you find the Bungle Bungles and the Pinnacles?", ["Western Australia (WA)", "New South Wales (NSW)", "Tasmania (TAS)", "Victoria (VIC)"], "Western Australia (WA)", "Australia"),
            Question("Australia is bounded southesternly by?", ["Vanuatu", "Papua New Guinea", "East Timor", "New Zealand"], "New Zealand", "Australia"),
            Question("The total number of states that make up Australia is?", ["10", "56", "6", "12"], "6", "Australia"),
            Question("The Queen is represented in each territory of Australia by?", ["Governor", "Administrator", "Chairman", "Minister"], "Governer", "Australia"),
            Question("Which of the following is not among the states of Australia?", ["Vancouver", "Victoria", "New South Wales", "Queensland"], "Vancouver", "Australia"),
            Question("The commonwealth parliament administers the following external territories except?", ["Christma s Island", "Jervis Bay Territory", "Saint Nicholas Island", "Coral Sea Island"], "Saint Nicholas Island", "Australia"),
            Question("The parliament of each states have the power legislate concerning the following except?", ["Health", "Education", "Natural Resources", "Transport"], "Natural Resoources", "Australia"),
            Question("Which state or territory of Australia has two widely-separated towns, both called Alligator Creek?", ["Queensland", "West Australia", "The Northern Territory", "Tasmania"], "Queensland", "Australia"),
            Question("Where was the former Premier of Queensland, Annastacia Palaszczuk, born?", ["Australia", "The Netherlands", "Durack", "New Zealand"], "Durack", "Australia"),
            Question("Who first sang, 'Australia, Australia, we love you from the heart; the liver, the kidneys, and the giblets, and every other part'?", ["Spike Milligan", "John Clease", "Graham Kennedy", "Dame Edna Everage"], "Spike Milligan", "Australia"),
            Question("What is the height of Ayer's Rock, or Uluru?", ["345 meters", "515 meters", "876 meters", "1002 meters"], "345 meters", "Australia"),
            Question("Which geographical region was crucial for spice trade?", ["Arabian Peninsula", "Strait of Malacca", "Malay Peninsula", "Plateau of Tibet"], "Strait of Malacca", "Asia"),
            Question("Which river is the longest in Asia?", ["Ganges", "Yangtze", "Mekong", "Euphrates"], "Yangtze", "Asia"),
            Question("Mount Everest, the world's tallest mountain, is located in which Asian country?", ["Nepal", "China", "India", "Bhutan"], "Nepal", "Asia"),
            Question("The Great Wall of China was primarily built to defend against invasions from which group of people?", ["Mongols", "Persians", "Vikings", "Huns"], "Huns", "Asia"),
            Question("The city of Tokyo is situated on which island?", ["Honshu", "Hokkaido", "Kyushu", "Shikoku"], "Honshu", "Asia"),
            Question("The Dead Sea, known for its high salt concentration, is bordered by which two countries?", ["Jordan and Israel", "Turkey and Syria", "Iran and Iraq", "Saudi Arabia and Yemen"], "Jordan and Israel", "Asia"),
            Question("The largest desert in Asia is the:", ["Arabian Desert", "Gobi Desert", "Thar Desert", "Syrian Desert"], "Gobi Desert", "Asia"),
            Question("Which Asian country is known as the 'Land of the Rising Sun'?", ["China", "South Korea", "Japan", "Thailand"], "Japan", "Asia"),
            Question("What is the largest country in Asia by land area?", ["China", "India", "Russia", "Indonesia"], "Russia", "Asia"),
            Question("The historic Silk Road was a network of trade routes that connected which two major regions?", ["Europe and Asia", "South America and North America", "Asia and Europe", "Australia and Asia"], "Asia and Europe", "Asia"),
            Question("What is the capital city of Malaysia?", ["Penang", "Kuala Lumpur", "Johor Bahru", "Malacca"], "Kuala Lumpur", "Asia"),
            Question("The island of Borneo is shared by Malaysia, Indonesia, and which other country?", ["Brunei", "Philippines", "Thailand", "Vietnam"], "Brunei", "Asia"),
            Question("Singapore is a city-state located at the southern tip of which larger country?", ["Thailand", "Malaysia", "Indonesia", "Philippines"], "Malaysia", "Asia"),
            Question("The famous Marina Bay Sands resort, with its distinctive rooftop pool, is a landmark in which city?", ["Jakarta", "Bangkok", "Singapore", "Kuala Lumpur"], "Singapore", "Asia"),
            Question("Singapore is known for its strict laws, and the ban on chewing gum is one of its unique regulations. What year was the ban implemented?", ["1965", "1980", "1992", "2004"], "1992", "Asia"),
            Question("What is the capital of Sudan?", ["Khartoum", "Asmara", "Djibouti", "Dodoma"], "Kharbutourn", "Africa"),
            Question("Zimbabew is in?", ["East Africa", "Central Africa", "West Africa", "North Africa"], "East Africa", "Africa"),
            Question("Largest country in East Africa is: ", ["Kenya", "Somalia", "Malawi", "Ethiopia"], "Ethiopia", "Africa"),
            Question("In North Africa there is: ", ["9 countries", "7 countries", "20 countries", "11 countries"], "7 countries", "Africa"),
            Question("Mount Kilimanjaro is located in which country?", ["Tazania", "Ghana", "Namibia", "South Africa"], "Tanzania", "Africa"),
            Question("The river that crosses Equator two times is?", ["Congo", "Nile", "limpopo", "Niger"], "Congo", "Africa"),
            Question("Which African country shares its boundary with Mediterranean Sea?", ["Libya", "Kenya", "Congo", "Uganda"], "Libya", "Africa"),
            Question("Blue Nile and White Nile meet at?", ["Khartoum", "Cairo", "Marrakesh", "Lagos"], "Khartooum", "Africa"),
            Question("Which river is the longest in Africa and the second-longest in the world?", ["Niger", "Zambezi", "Mile", "Congo"], "Nile", "Africa"),
            Question("The largest lake in Africa by surface area is: ", ["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"], "Lake Victoria", "Africa"),
            Question("Which desert is often referred to as the 'Desert of Deserts' and covers parts of North Africa?", ["Sahara Desert", "Namib Desert", "Kalahari Desert", "Libyan Desert"], "Sahara Desert", "Africa"),
            Question("The island of Madagascar is part of the which ocean?", ["Indian Ocean", "Atlantic Ocean", "Pacific Ocean", "Southern Ocean"], "Indian Ocean", "Africa"),
            Question("The city of Marrakech, known for its vibrant markets and historical significance, is located in which African country?", ["Egypt", "Morocco", "Tunisia", "Algeria"], "Morocco", "Africa"),
            Question("The island of Zanzibar, known for its beautiful beaches and rich history, is part of which East African country?", ["Kenya", "Tanzania", "Seychelles", "Madagascar"], "Tanzania", "Africa"),
            Question("The Great Escarpment, a steep slope separating the coastal lowlands from the interior plateau, runs along the eastern edge of which African country?", ["Kenya", "Tanzania", "South Africa", "Mozambique"], "South Africa", "Africa"),
            Question("Which river is the longest in Europe?", ["Seine", "Rhine", "Danube", "Volga"], "Volga", "Europe"),
            Question("The city of Prague, famous for its stunning architecture and historic sites, is the capital of which European country?", ["Austria", "Hungary", "Czech Republic", "Poland"], "Czech Republic", "Europe"),
            Question("The region known as the 'Cradle of Renaissance' and home to famous cities like Florence, Venice, and Rome is located in which European country?", ["Greece", "Spain", "Italy", "France"], "Italy", "Europe"),
            Question("The fjords, steep-sided valleys carved by glaciers, are a distinctive geographical feature of which European country?", ["Norway", "Iceland", "Ireland", "Scotland"], "Norway", "Europe"),
            Question("How many countries are there in Europe?", ["47", "48", "49", "50"], "50", "Europe"),
            Question("What defines the southeast boundary of Europe with Asia?", ["Nile River", "Ural River", "Niger River", "Mississippi River"], "Ural River", "Europe"),
            Question("Which of these water bodies separates Europe from Africa?", ["Ural River", "Mississippi River", "Mediterranean Sea", "Red Sea"], "Mediterranean Sea", "Europe"),
            Question("Which of these is not an European country?", ["Austria", "Cyprus", "Slovakia", "Singapore"], "Singapore", "Europe"),
            Question("The Iberian Peninsula is shared by Spain and which other country?", ["France", "Italy", "Portugal", "Greece"], "Portugal", "Europe"),
            Question("The Alps mountain range stretches across several European countries. Which one of these countries is NOT part of the Alps?", ["Switzerland", "Austria", "Norway", "France"], "Norway", "Europe"),
            Question("The famous historic site Stonehenge is located in which European country?", ["Ireland", "France", "United Kingdom", "Germany"], "United Kingdom", "Europe"),
            Question("The Balkan Peninsula is known for its diverse cultures and historical conflicts. Which country is not part of the Balkan Peninsula?", ["Greece", "Bulgaria", "Hungary", "Romania"], "Hungary", "Europe"),
            Question("The city of Dublin is the capital of which European country?", ["Norway", "Sweden", "Ireland", "Denmark"], "Ireland", "Europe"),
            Question("Which of these is not an island in Europe?", ["Iceland", "Ireland", "Queensland", "Great Britain"], "Queensland", "Europe"),
            Question("What is the western boundary of Europe?", ["Atlantic Ocean", "Pacific Ocean", "Mediterranean Sea", "Black Sea"], "Altantic Ocean", "Europe"),
            Question("What ocean boarders North America to the East?", ["Atlantic Ocean", "Gulf of Mexico", "Pacific Ocean", "Oceania"], "Atlantic Ocean", "North America"),
            Question("What are the three largest countries in North America?", ["Russia, United States, China", "Mexico, Italy, Russia", "Mexico, Canada, United States", "Singapore, Malaysia, Thailand"], "Mexico, Canada, United States", "North America"),
            Question("North America is the only continent with what?", ["Every kind of climate", "Landforms", "Countries", "Poeple"], "Every kind of climate", "North America"),
            Question("Which of the following is the longest river in North America?", ["Rio Grande", "Missouri", "Mississippi", "Amazon"], "Mississippi", "North America"),
            Question("This is the largest North America city.", ["Phoenix", "Mexico City", "New York City", "Chicago"], "Mexico City", "North America"),
            Question("How many countries make up the continent of North America?", ["3", "9", "12", "24"], "24", "North America"),
            Question("How many states does British Colombia border?", ["1", "2", "3" ,"4"], "4", "North America"),
            Question("The city of Vancouver is located in which Canadian province?", ["Ontario", "Quebec", "British Colombia", "Alberta"], "British Colombia", "North America"),
            Question("The Appalachian Mountains stretch across which part of North America?", ["Western United States", "Eastern United States", "Central Canada", "Western Mexico"], "Eastern United States", "North America"),
            Question("The Great Lakes are a group of large freshwater lakes located in which two countries?", ["United States and Canada", "United States and Mexico", "Canada and Mexico", "Canada and Greenland"], "United States and Canada", "North America"),
            Question("The capital of Mexico is:", ["Cancún", "Monterrey", "Mexico City", "Guadalajara"], "Mexico City", "North America"),
            Question("The Rocky Mountains extend through which part of North America?", ["Eastern United States", "Central Canada", "Western United States", "Eastern Mexico"], "Western United States", "North America"),
            Question("The province of Alberta in Canada is known for its production of which natural resource?", ["Timber", "Oil", "Coal", "Iron Ore"], "Oil", "North America"),
            Question("The state of Hawaii is composed of a group of islands in which ocean?", ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Artic Ocean"], "Pacific Ocean", "North America"),
            Question("Which U.S. state is known as the 'Sunshine State' and is famous for its beaches and theme parks?", ["California", "Florida", "Texas", "Arizona"], "Florida", "North America"),
            Question("Which one is the biggest country (by area) in South America?", ["Chile", "Venezuela", "Argentina", "Brazil"], "Chile", "South America"),
            Question("The lake 'Titicaca' is on the border of which two nations?", ["Peru and Ecuador", "Brazil and Bolivia", "Colombia and Chile", "Bolivia and Peru"], "Bolivia and Peru", "South America"),
            Question("Which river is the longest in South America and the second-longest in the world?", ["Amazon River", "Orinoco River", "Paraná River", "Magdalena River"], "Amazon River", "South America"),
            Question("Machu Picchu, an ancient Incan city and UNESCO World Heritage Site, is located in which South American country?", ["Colombia", "Ecuador", "Peru", "Bolivia"], "Peru", "South America"),
            Question("The largest rainforest in the world, known for its incredible biodiversity, is found in which part of South America?", ["The Andes Mountain", "The Pampas", "THe Atacama Desert", "The Amazon Basin"], "The Amazon Basin", "South America"),
            Question("The capital city of Argentina is:", ["Santiago", "Montevideo", "Buenos Aires", "Caracas"], "Buenos Aires", "South America"),
            Question("The Atacama Desert, one of the driest places on Earth, is located in which South American country?", ["Chile", "Peru", "Bolivia", "Argentina"], "Chile", "South America"),
            Question("The Galápagos Islands, known for their unique wildlife and contributions to Charles Darwin's theory of evolution, are part of which country?", ["Brazil", "Ecuador", "Colombia", "Venezuela"], "Ecuador", "South America"),
            Question("The Andes Mountains, the longest mountain range in the world, stretch through which South American countries?", ["Brazil and Argentina", "Chile and Colombia", "Peru and Bolivia", "Venezuela nad Ecuador"], "Peru and Bolivia", "South America"),
            Question("he world's highest waterfall, Angel Falls, is located in which South American country?", ["Venezuela", "Brazil", "Colombia", "Guyana"], "Venezuela", "South America"),
            Question("The southernmost city in the world, Ushuaia, is located in which South American country?", ["Chile", "Argentina", "Uruguay", "Paraguay"], "Argentina", "South America"),
            Question("The Pantanal, a vast tropical wetland area, is located primarily in which South American country?", ["Colombia", "Brazil", "Peru", "Bolivia"], "Brazil", "South America"),
            Question("The world's largest salt flat, Salar de Uyuni, is located in which South American country?", ["Argentina", "Chile", "Peru", "Bolivia"], "Bolovia", "South America"),
            Question("Easter Island, known for its iconic stone statues called 'moai', is a territory of which South American country?", ["Chile", "Argentina", "Brazil", "Uruguay"], "Chile", "South America"),
            Question("The Guiana Shield, a geological formation of ancient rock, is located in which part of South America?", ["Northern", "Western", "Central", "Southern"], "Northern", "South America")]
